#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "SVTDensityField.generated.h"

class UDualContour;
class UStaticSparseVolumeTexture;

UENUM(BlueprintType)
enum class ESVTDensityFieldFit : uint8
{
	Fill UMETA(DisplayName = "Fill"),
	Contain UMETA(DisplayName = "Contain"),
	Cover UMETA(DisplayName = "Cover")
};

UENUM(BlueprintType)
enum class ESVTDensityFieldAttribute : uint8
{
	AttributesA_R UMETA(DisplayName = "Attributes A - R"),
	AttributesA_G UMETA(DisplayName = "Attributes A - G"),
	AttributesA_B UMETA(DisplayName = "Attributes A - B"),
	AttributesA_A UMETA(DisplayName = "Attributes A - A"),
	AttributesB_R UMETA(DisplayName = "Attributes B - R"),
	AttributesB_G UMETA(DisplayName = "Attributes B - G"),
	AttributesB_B UMETA(DisplayName = "Attributes B - B"),
	AttributesB_A UMETA(DisplayName = "Attributes B - A")
};

/** Persistent density field generated by sampling a static sparse volume texture. */
UCLASS(BlueprintType)
class DUALCONTOURMESH_API USVTDensityField : public UObject
{
	GENERATED_BODY()

public:
	USVTDensityField();

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Instanced, Category = "Density Field", meta = (ShowOnlyInnerProperties))
	TObjectPtr<UDualContour> DualContour;

#if WITH_EDITORONLY_DATA
	/** Source data is intentionally stripped from cooked packages; only DualContour is shipped. */
	UPROPERTY(EditAnywhere, Category = "Source")
	TObjectPtr<UStaticSparseVolumeTexture> SourceSparseVolumeTexture;

	UPROPERTY(EditAnywhere, Category = "Source")
	ESVTDensityFieldFit Fit = ESVTDensityFieldFit::Contain;

	UPROPERTY(EditAnywhere, Category = "Source")
	ESVTDensityFieldAttribute DensityAttribute = ESVTDensityFieldAttribute::AttributesA_R;

	UPROPERTY(EditAnywhere, Category = "Source", meta = (ClampMin = "0.0"))
	float DensityScale = 1.f;

	UPROPERTY(EditAnywhere, Category = "Source")
	float DensityBias = 0.f;

	/** Editor preview scale for ASparseVolumeTextureViewer. */
	UPROPERTY(EditAnywhere, Category = "Preview")
	FVector SVTScale = FVector::OneVector;

	UPROPERTY(VisibleAnywhere, Transient, Category = "Preview")
	int32 GenerationRevision = 0;
#endif

#if WITH_EDITOR
	UFUNCTION(CallInEditor, Category = "Density Field")
	bool SampleSparseVolumeTexture();
#endif
};
