#pragma once

#include "CoreMinimal.h"
#include "DualContour.h"
#include "SVTDualContour.generated.h"

class UStaticSparseVolumeTexture;

UENUM(BlueprintType)
enum class ESVTDualContourFit : uint8
{
	Fill UMETA(DisplayName = "Fill"),
	Contain UMETA(DisplayName = "Contain"),
	Cover UMETA(DisplayName = "Cover")
};

UENUM(BlueprintType)
enum class ESVTDualContourAttribute : uint8
{
	AttributesA_R UMETA(DisplayName = "Attributes A - R"),
	AttributesA_G UMETA(DisplayName = "Attributes A - G"),
	AttributesA_B UMETA(DisplayName = "Attributes A - B"),
	AttributesA_A UMETA(DisplayName = "Attributes A - A"),
	AttributesB_R UMETA(DisplayName = "Attributes B - R"),
	AttributesB_G UMETA(DisplayName = "Attributes B - G"),
	AttributesB_B UMETA(DisplayName = "Attributes B - B"),
	AttributesB_A UMETA(DisplayName = "Attributes B - A")
};

/** Persistent dual contour generated by sampling a static sparse volume texture. */
UCLASS(BlueprintType)
class DUALCONTOURMESH_API USVTDualContour : public UDualContour
{
	GENERATED_BODY()

public:
#if WITH_EDITORONLY_DATA
	/** Source data is intentionally stripped from cooked packages; only generated dual-contour data is shipped. */
	UPROPERTY(EditAnywhere, Category = "Source")
	TObjectPtr<UStaticSparseVolumeTexture> SourceSparseVolumeTexture;

	UPROPERTY(EditAnywhere, Category = "Source")
	ESVTDualContourFit Fit = ESVTDualContourFit::Contain;

	UPROPERTY(EditAnywhere, Category = "Source")
	ESVTDualContourAttribute DensityAttribute = ESVTDualContourAttribute::AttributesA_R;

	UPROPERTY(EditAnywhere, Category = "Source", meta = (ClampMin = "0.0"))
	float DensityScale = 1.f;

	UPROPERTY(EditAnywhere, Category = "Source")
	float DensityBias = 0.f;

	/** Editor preview scale for ASparseVolumeTextureViewer. */
	UPROPERTY(EditAnywhere, Category = "Preview")
	FVector SVTScale = FVector::OneVector;

	UPROPERTY(VisibleAnywhere, Transient, Category = "Preview")
	int32 GenerationRevision = 0;
#endif

#if WITH_EDITOR
	UFUNCTION(CallInEditor, Category = "SVT Dual Contour")
	bool SampleSparseVolumeTexture();

	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
#endif
};
