#pragma once

#include "CoreMinimal.h"
#include "DualContour.h"
#include "VolumeSampledDualContour.generated.h"

class UVolumeSampler;

/** Persistent DualContour generated by baking any VolumeSampler. */
UCLASS(BlueprintType)
class DUALCONTOURMESH_API UVolumeSampledDualContour : public UDualContour
{
	GENERATED_BODY()

public:
#if WITH_EDITORONLY_DATA
	/** Editor-only source sampler. Cooked assets retain only the generated DualContour data. */
	UPROPERTY(EditAnywhere, Instanced, Category = "Source", meta = (ShowOnlyInnerProperties))
	TObjectPtr<UVolumeSampler> VolumeSampler;

	/** Translation, rotation and scale applied to VolumeSampler about its pivot. */
	UPROPERTY(EditAnywhere, Category = "Source")
	FTransform SampleTransform = FTransform::Identity;

	UPROPERTY(VisibleAnywhere, Transient, Category = "Preview")
	int32 GenerationRevision = 0;
#endif

#if WITH_EDITOR
	UFUNCTION(CallInEditor, Category = "Volume Sampled Dual Contour")
	bool SampleVolume();

	void NotifySamplerChanged();
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
#endif
};
